servers = [
  {
    :hostname => "web",
    :ip => "192.168.100.10",
    :box => "centos/8",
    :ram => 1024,
    :cpu => 2,
    :disk_size => 4,
  },
  {
    :hostname => "db",
    :ip => "192.168.100.11",
    :box => "centos/8",
    :ram => 2048,
    :cpu => 2,
    :disk_size => 4,
  },
]

Vagrant.configure(2) do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      # node.vm.network "private_network", ip: machine[:ip]
      nested_host.vm.provider :libvirt do |domain|
        domain.memory = machine[:ram]
        domain.cpus = machine[:cpu]
        domain.nested = true
        domain.volume_cache = "none"
        domain.cpu_mode = "host-passthrough"
        domain.machine_virtual_size = machine[:disk_size]
      end
    end
  end
end
